name: bifacial_radiancedocs
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - numpy=1.14.2
    - scipy=0.19.1
    - pytables
    - pandas=0.24.0
    - pytz=2018.9
    - ephem
    - numba
    - ipython=6.3
    - matplotlib=2.2.3
    - siphon=0.7.0
    - sphinx=1.7.2
    - netCDF4=1.3.1
    - hdf4=4.2.12
    - sphinx_rtd_theme
    - pvlib=0.6.0
